### ISSUE TITLE
Test fail : "no variant or associated item named 'ed25519' found"

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/counter#7]
Hello,
Test currently failing with the error: 
`no variant or associated item named 'ed25519' found`

![image](https://user-images.githubusercontent.com/8867156/120825296-18219480-c50e-11eb-8e11-75f39ef988ce.png)

Steps:
$ make prepare
$ make test

**Comment by deuszex** [comment]
The compilation goes with versions 1.2.0, but the used API is 1.1.1. 
use `SecretKey::ed25519_from_bytes([1u8;32]).unwrap().into();` instead
A PR with this fix has already been merged-
